<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ApplicationIcon>Resources\Picture\ApplicationIcon.ico</ApplicationIcon>
    <AssemblyVersion>1.0.2026.1</AssemblyVersion>
    <FileVersion>1.0.2026.1</FileVersion>
    <Authors>MinimalWPF</Authors>
    <Company>MinimalWPF</Company>
    <Product>MinimalWPF</Product>
    <Description>MinimalWPF NET10 V6 Template </Description>
    <PackageId>MinimalWPF</PackageId>
    <AssemblyName>SnippetManager</AssemblyName>
    <AssemblyTitle>MinimalWPF</AssemblyTitle>
    <RootNamespace>SnippetManager</RootNamespace>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Sound\AccessAllowedTone.wav" />
    <None Remove="Resources\Sound\ArabianMysteryNotification.wav" />
    <None Remove="Resources\Sound\ArcadeMagicNotification.wav" />
    <None Remove="Resources\Sound\BellNotification.wav" />
    <None Remove="Resources\Sound\CashMachineKeyPress.wav" />
    <None Remove="Resources\Sound\ClearAnnounceTones.wav" />
    <None Remove="Resources\Sound\ConfirmationTone.wav" />
    <None Remove="Resources\Sound\CorrectAnswerReward.wav" />
    <None Remove="Resources\Sound\GuitarNotificationAlert.wav" />
    <None Remove="Resources\Sound\HappyBellsNotification.wav" />
    <None Remove="Resources\Sound\MagicMarimba.wav" />
    <None Remove="Resources\Sound\MelodicalFluteMusicNotification.wav" />
    <None Remove="Resources\Sound\MusicalAlertNotification.wav" />
    <None Remove="Resources\Sound\MusicalReveal.wav" />
    <None Remove="Resources\Sound\OrchestralEmergencyAlarm.wav" />
    <None Remove="Resources\Sound\PositiveNotification.wav" />
    <None Remove="Resources\Sound\SoftwareInterfaceBack.wav" />
    <None Remove="Resources\Sound\SoundCapture.wav" />
    <None Remove="Resources\Sound\SoundClick.wav" />
    <None Remove="Resources\Sound\SoundFailure.wav" />
    <None Remove="Resources\Sound\SoundMonitorPowerOff.wav" />
    <None Remove="Resources\Sound\SoundNews.wav" />
    <None Remove="Resources\Sound\SoundNotice.wav" />
    <None Remove="Resources\Sound\SoundOn.wav" />
    <None Remove="Resources\Sound\SoundSignal.wav" />
    <None Remove="Resources\Sound\SoundSuccess.wav" />
    <None Remove="Resources\Sound\SuccessTone.wav" />
    <None Remove="Resources\Sound\UpliftingFluteNotification.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Picture\ApplicationIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Sound\AccessAllowedTone.wav" />
    <EmbeddedResource Include="Resources\Sound\ArabianMysteryNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\ArcadeMagicNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\BellNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\CashMachineKeyPress.wav" />
    <EmbeddedResource Include="Resources\Sound\ClearAnnounceTones.wav" />
    <EmbeddedResource Include="Resources\Sound\ConfirmationTone.wav" />
    <EmbeddedResource Include="Resources\Sound\CorrectAnswerReward.wav" />
    <EmbeddedResource Include="Resources\Sound\GuitarNotificationAlert.wav" />
    <EmbeddedResource Include="Resources\Sound\HappyBellsNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\MagicMarimba.wav" />
    <EmbeddedResource Include="Resources\Sound\MelodicalFluteMusicNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\MusicalAlertNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\MusicalReveal.wav" />
    <EmbeddedResource Include="Resources\Sound\OrchestralEmergencyAlarm.wav" />
    <EmbeddedResource Include="Resources\Sound\PositiveNotification.wav" />
    <EmbeddedResource Include="Resources\Sound\SoftwareInterfaceBack.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundCapture.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundClick.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundFailure.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundMonitorPowerOff.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundNews.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundNotice.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundOn.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundSignal.wav" />
    <EmbeddedResource Include="Resources\Sound\SoundSuccess.wav" />
    <EmbeddedResource Include="Resources\Sound\SuccessTone.wav" />
    <EmbeddedResource Include="Resources\Sound\UpliftingFluteNotification.wav" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Picture\ApplicationIcon.ico" />
    <Resource Include="Resources\Picture\ApplicationIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Message\" />
    <Folder Include="Core\Settings\" />
    <Folder Include="Data\Core\" />
    <Folder Include="Resources\Style\" />
    <Folder Include="Resources\Localization\" />
    <Folder Include="TemplateCore\EventAggregator\" />
    <Folder Include="TemplateCore\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ViewUC\SourceSnippetsDetailUC.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ViewUC\XamlGrafikUC.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="ViewUC\SourceSnippetsUC.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
